stages:
  - deploy

deploy_dev:
  only:
    refs:
      - development
  stage: deploy
  tags:
    - development
  before_script:
    - echo "creating env files"
    - cat "$DEV_KEYS" | base64 --decode > "$(pwd)/.env"
  script:
    - docker-compose -f development.yml up -d --build
    - docker-compose -f development.yml run --rm django python manage.py makemigrations
    - docker-compose -f development.yml run --rm django python manage.py migrate
  environment:
    name: development
    url: https://{{cookiecutter.dev_domain_name}}

deploy_prod:
  only:
    refs:
      - main
  stage: deploy
  tags:
    - production
  before_script:
    - echo "creating env files"
    - cat "$PROD_KEYS" | base64 --decode > "$(pwd)/.env"
  script:
    - docker-compose -f production.yml up -d --build
    - docker-compose -f production.yml run --rm django python manage.py makemigrations
    - docker-compose -f production.yml run --rm django python manage.py migrate
  environment:
    name: production
    url: https://{{cookiecutter.domain_name}}
