version: '3'

volumes:
  development_traefik: {}

services:
  django:
    build:
      context: backend
    image: {{cookiecutter.project_slug}}_development_django
    env_file:
      - ./.env
    command: /start

  traefik:
    build:
      context: ..
      dockerfile: ./traefik/Dockerfile
      args:
        - BUILD_ENVIRONMENT=development
    image: {{cookiecutter.project_slug}}_development_traefik
    depends_on:
      - django
    volumes:
      - development_traefik:/etc/traefik/acme:z
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
