version: "3"

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django:
    build:
      context: backend
    image: {{cookiecutter.project_slug}}_django_local
    depends_on:
      - postgres
    env_file:
      - ./.env
    command: /start
    ports:
      - "5000:5000"

  postgres:
    image: postgres
    container_name: {{cookiecutter.project_slug}}_postgres_local
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    env_file:
      - .env
    ports:
      - "5432:5432"
