version: "3"

volumes:
  local_postgres_data: {}

services:
  django:
    build:
      context: backend
    image: {{cookiecutter.project_slug}}_django_local
    depends_on:
      - postgres
    env_file:
      - ./.env
    command: /start
    ports:
      - "5000:5000"

  postgres:
    image: postgres
    container_name: {{cookiecutter.project_slug}}_postgres_local
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
    env_file:
      - .env
    ports:
      - "5432:5432"

  redis:
    container_name: {{cookiecutter.project_slug}}_redis_local
    image: redis:6
    ports:
      - "6379:6379"
