#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

postgres_ready() {
python << END
import sys

import psycopg2

try:
    dsn = "${POSTGRES_DSN}"
    dsn_ = dsn.replace("postgis://", "postgresql://") if dsn.startswith("postgis://") else dsn
    psycopg2.connect(dsn_)
except psycopg2.OperationalError as e:
    print(e)
    sys.exit(-1)
sys.exit(0)

END
}
until postgres_ready; do
  >&2 echo 'Waiting for PostgreSQL to become available...'
  sleep 1
done
>&2 echo 'PostgreSQL is available'

exec "$@"
