#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python /app/manage.py collectstatic --noinput

/usr/local/bin/gunicorn backend.wsgi:application -b 0.0.0.0:5000 \
  --workers=5 \
  --threads=2 \
  --max-requests=25 \
  --access-logfile=- \
  --access-logformat='%({X-Real-IP}i)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s" "%(M)sms"'
