log:
  level: DEBUG

entryPoints:
  web:
    address: ":80"

http:
  routers:
    web-router:
      rule: "Host(`localhost`)"
      entryPoints:
        - web
      middlewares:
        - csrf
        - test-compress
      service: django

  middlewares:
    csrf:
      headers:
        hostsProxyHeaders: ["X-CSRFToken"]
    test-compress:
      compress:
        excludedContentTypes:
          - text/event-stream

  services:
    django:
      loadBalancer:
        servers:
          - url: http://django:5000

api:
  insecure: true

providers:
  file:
    filename: /etc/traefik/traefik.yml
    watch: true
